db:
  host: "hs-postgres"
  port: 5432
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  name: "hash-service-db"
 
redis:
  host: "hs-redis"
  port: 6379
  # user: "${REDIS_USER}"
  # password: "${REDIS_PASSWORD}"